### ISSUE TITLE
Be able to install a specific version of `chefdk`

### ISSUE THREAD

**Issue by afiune** [chef-cookbooks/delivery_build#1]
As a user I would like to be able to control the way I upgrade `chefdk` on my build-nodes so my development team can move at the same time with the pipeline.

**Comment by thommay** [comment]
note that this is already supported on windows using `node['delivery_build']['chefdk_version']`.

**Comment by afiune** [comment]
True that! Making sure this also happen on Unix .. :smile:

**Comment by afiune** [comment]
Although I am not sure how `node['delivery_build']['chefdk_version']` get set since it does not exist on the `attributes` file..
