### ISSUE TITLE
Incorrect path to push-jobs when adding cert

### ISSUE THREAD

**Issue by stephenlauck** [chef-cookbooks/delivery_build#5]
The hardcoded path is incorrect for adding the cacert.pem to push jobs certs.

```
ssh vagrant@192.168.33.67 -i /Users/elliott/.vagrant.d/insecure_private_key
Warning: Permanently added '192.168.33.67' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Feb  9 17:58:34 2016 from 192.168.33.1
vagrant@builder-local:~$ ls /opt/
chef/                      chefdk/                    delivery-cli/              push-jobs-client/          VBoxGuestAdditions-5.0.12/
vagrant@builder-local:~$ cat /opt/push-jobs-client/embedded/ssl/certs/cacert.pem
```

The following code should be updated:

`cacert_pem DeliveryBuild::PathHelper.omnibus_embedded_path('opscode-push-jobs-client', 'ssl/certs/cacert.pem')`

should be updated to remove 'opscode':

`cacert_pem DeliveryBuild::PathHelper.omnibus_embedded_path('push-jobs-client', 'ssl/certs/cacert.pem')`

`No such file or directory @ rb_sysopen - /opt/opscode-push-jobs-client/embedded/ssl/certs/cacert.pem``

**Comment by afiune** [comment]
What version of push-jobs do you have installed?
